name: CI/CD with Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install and test
        run: |
          npm install 
          npm test

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .

      - name: Test Docker image
        run: |
          docker run -d -p 80:80 --name test-container ${{ github.repository }}:${{ github.sha }} 
          sleep 10 
          curl -f http://localhost:80 || exit 1 
          docker stop test-container

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . -t myapp

      - name: Deploy Node.js code
        uses: azure/webapps-deploy@v2
        with:
          app-name: test-website
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

